# Generated by Django 4.2.1 on 2023-06-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
